name: Publish Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Replace with your desired Python version

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Build Release
      run: |
        poetry build

    - name: Publish to PyPI
      run: |
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }} --verbose
