name: Run Tests

on:
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # Specify the Python versions you want to test against

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        pip install poetry

    - name: Display dependencies
      run: |
        poetry lock
        poetry show --tree
        poetry env info

    - name: Install Dependencies using poetry
      run: |
        poetry install

    - name: Run Tests
      run: |
        poetry run pytest

    - name: Lint with pylint
      run: |
        poetry run pylint src