name: Run Tests

on:
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # It turns out ubuntu python environments do not consider distutils
    # an important core feature. We need it. Install it
    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils

    - name: Verify Issue
      run: |
        pip wheel --no-cache-dir --use-pep517 "numpy (==1.24.4)"

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install Dependencies using poetry
      run: |
        poetry install

    - name: Run Tests
      run: |
        poetry run pytest

    - name: Lint with pylint
      run: |
        poetry run pylint